services: 
  webapplication: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    image: trackweather/localtrackweather:v1 
    container_name: webapplication 
    ports: 
     - "5180:8080" 
    environment: 
     - ASPNETCORE_ENVIRONMENT=Development 
     - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=TrackWeatherDb;User Id=sa;Password=Password123#;Trusted_Connection=False;TrustServerCertificate=true 
    networks: 
     - my_network 
 
networks: 
  my_network: 
    driver: bridge